title: "Ethics in Network Science Research & Practice"
description: "NetSci 2026 Satellite · Boston · Sunday, June 1, 2026"

# Set these two correctly:
url: "https://ethics-complexity.github.io"
baseurl: "/netsci2026-ethics"

remote_theme: "mmistakes/minimal-mistakes@4.27.3"

plugins:
  - jekyll-include-cache

minimal_mistakes_skin: "mint"   # try "air", "contrast", "default", "dark", etc.

# Optional but nice defaults for a clean single-page site
defaults:
  - scope:
      path: ""
    values:
      layout: single
      classes: wide
      author_profile: false
      toc: false
      sidebar: null
